### ISSUE TITLE
Error: Call to undefined function features_get_default() on GUI install

### ISSUE THREAD

**Issue by deirdrehall** [NuCivic/dkan#1732]
I am trying to install dkan-drops-7-master (the fully built version) under xampp in Windows 7 Professional. Every attempt, I get to DKAN final setup tasks and get the error:

An AJAX HTTP error occurred. HTTP Result Code: 500 Debugging information follows. Path: http://localhost/dkan/install.php?profile=dkan&locale=en&id=2&op=do StatusText: Service unavailable (with message) ResponseText: Error: Call to undefined function features_get_default() in dkan_build_menu_links() (line 270 of C:\xampp\htdocs\dkan\profiles\dkan\dkan.profile).

Is there a way to fix this and proceed?

**Comment by dafeder** [comment]
Hi @deirdrehall. This has been a very tough bug to squash and has been around for a while. I can tell you that in almost all cases the site does build just fine, and if you navigate to your new DKAN site you'll find everything as it should be. Also, if you install with Drush rather than the web interface I would not expect to get any errors. I will keep this open though and take another pass at fixing.

Let us know how it goes.

**Comment by deirdrehall** [comment]
If I nagivate to the site, I get a growing number of errors such as: 
Notice: Undefined offset: 1 in nuboot_radix_preprocess() (line 44 of C:\xampp\htdocs\dkan\profiles\dkan\themes\nuboot_radix\includes\panel.inc).
Notice: Undefined offset: 1 in nuboot_radix_preprocess() (line 44 of C:\xampp\htdocs\dkan\profiles\dkan\themes\nuboot_radix\includes\panel.inc).
Notice: Undefined offset: 1 in nuboot_radix_preprocess() (line 44 of C:\xampp\htdocs\dkan\profiles\dkan\themes\nuboot_radix\includes\panel.inc).
Notice: Undefined offset: 1 in nuboot_radix_preprocess() (line 44 of C:\xampp\htdocs\dkan\profiles\dkan\themes\nuboot_radix\includes\panel.inc).
Notice: Undefined offset: 1 in nuboot_radix_preprocess() (line 44 of C:\xampp\htdocs\dkan\profiles\dkan\themes\nuboot_radix\includes\panel.inc).
Notice: Undefined offset: 1 in nuboot_radix_preprocess() (line 44 of C:\xampp\htdocs\dkan\profiles\dkan\themes\nuboot_radix\includes\panel.inc).
Notice: Undefined offset: 1 in nuboot_radix_preprocess() (line 44 of C:\xampp\htdocs\dkan\profiles\dkan\themes\nuboot_radix\includes\panel.inc).
Notice: Undefined variable: front_nid in nuboot_radix_preprocess() (line 48 of C:\xampp\htdocs\dkan\profiles\dkan\themes\nuboot_radix\includes\panel.inc).
Notice: Undefined offset: 1 in nuboot_radix_preprocess() (line 44 of C:\xampp\htdocs\dkan\profiles\dkan\themes\nuboot_radix\includes\panel.inc).
Notice: Undefined variable: front_nid in nuboot_radix_preprocess() (line 48 of C:\xampp\htdocs\dkan\profiles\dkan\themes\nuboot_radix\includes\panel.inc).
Notice: Undefined offset: 1 in nuboot_radix_preprocess() (line 44 of C:\xampp\htdocs\dkan\profiles\dkan\themes\nuboot_radix\includes\panel.inc).
Notice: Undefined variable: front_nid in nuboot_radix_preprocess() (line 48 of C:\xampp\htdocs\dkan\profiles\dkan\themes\nuboot_radix\includes\panel.inc).
Notice: Undefined offset: 1 in nuboot_radix_preprocess() (line 44 of C:\xampp\htdocs\dkan\profiles\dkan\themes\nuboot_radix\includes\panel.inc).
Notice: Undefined variable: front_nid in nuboot_radix_preprocess() (line 48 of C:\xampp\htdocs\dkan\profiles\dkan\themes\nuboot_radix\includes\panel.inc).
Notice: Undefined offset: 1 in nuboot_radix_preprocess() (line 44 of C:\xampp\htdocs\dkan\profiles\dkan\themes\nuboot_radix\includes\panel.inc).
Notice: Undefined variable: front_nid in nuboot_radix_preprocess() (line 48 of C:\xampp\htdocs\dkan\profiles\dkan\themes\nuboot_radix\includes\panel.inc).

I figured those were somehow related to the installation problems.

**Comment by acouch** [comment]
@deirdrehall Can you try installing via drush? ``drush site-install dkan`` instead of via the UI?

**Comment by deirdrehall** [comment]
I have no idea if I'm actually doing this right, but it returned:

c:\xampp\htdocs\dkan>drush site-install dkan --db-url="mysql://xxx:xxx@localhost/drupal"
You are about to create a sites/default/files directory and create a sites/default/settings.php file and DROP all tables in your 'drupal' database. Do you wantto continue? (y/n): y
mysql: [Warning] Using a password on the command line interface can be insecure.

Starting Drupal installation. This takes a few seconds ...                  [ok]

Drush command terminated abnormally due to an unrecoverable error.       [error]

Error: syntax error, unexpected '[' in
C:\xampp\htdocs\dkan\profiles\dkan\dkan.profile, line 507

**Comment by acouch** [comment]
I suspect this is because you are using an older version of PHP which does not support the "[" array notation (https://github.com/NuCivic/dkan/blob/7.x-1.x/dkan.profile#L506). Can you try on an environment that is at least PHP 5.4 or higher? Looks like the latest XAMP has 5.6 or 7 https://www.apachefriends.org/download.html

**Comment by deirdrehall** [comment]
My installation of xampp has PHP Version 7.1.1 (is this going to be a problem?).  It looks like my installation of Drush 6 was using the older PHP version on its own. I uninstalled it and installed drush 7 using composer.

**Comment by acouch** [comment]
I think PHP 7.1.1 should be fine. Let me see if I can reproduce.

**Comment by deirdrehall** [comment]
The install succeeded, but had errors using drush as well. 

For example:
Migration failed with source plugin exception: <em                   [error]
class="placeholder">A non-numeric value encountered
File
C:\xampp\htdocs\dkan\profiles\dkan\modules\dkan\dkan_migrate_base\dkan_migrate_base.migrate.inc,
line 68</em>, in <em
class="placeholder">C:\xampp\htdocs\dkan\profiles\dkan\modules\contrib\migrate\includes\base.inc</em>:<em
class="placeholder">707</em>
Migration failed with source plugin exception: <em                   [error]
class="placeholder">A non-numeric value encountered
File

And errors above still exist when I go to the site itself:

Notice: Undefined offset: 1 in nuboot_radix_preprocess() (line 44 of C:\xampp\htdocs\dkan\profiles\dkan\themes\nuboot_radix\includes\panel.inc).
(and etc)

**Comment by oriole9g** [comment]
Same problem. When I install from scrath the last version 7.x-1.13.1 from UI I get a site with the same error:

`Notice: Undefined offset: 1 in nuboot_radix_preprocess() (line 45 of /var/local/html/dadesobertes/profiles/dkan/themes/nuboot_radix/includes/panel.inc).`

During the install I have seen this notices in the "DKAN final setup tasks > enabled DKAN Default Content" phase:

`Migration failed with source plugin exception: file_get_contents(profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_default_content/data/group_show?id=61803702-1d76-4aac-92a1-7a4de4cd26eb.json): failed to open stream: No such file or directory File /var/local/html/dadesobertes/profiles/dkan/modules/dkan/dkan_migrate_base/dkan_migrate_base.migrate.inc, line 223, in /var/local/html/dadesobertes/profiles/dkan/modules/contrib/migrate/includes/base.inc:707
Migration failed with source plugin exception: file_get_contents(profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_default_content/data/resource_show?id=37971f0c-a5e8-4c0c-9dbc-d6fe5fb54607.json): failed to open stream: No such file or directory File /var/local/html/dadesobertes/profiles/dkan/modules/dkan/dkan_migrate_base/dkan_migrate_base.migrate.inc, line 223, in /var/local/html/dadesobertes/profiles/dkan/modules/contrib/migrate/includes/base.inc:707
Migration failed with source plugin exception: file_get_contents(profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_default_content/data/package_show?id=wisconsin-polling-places.json): failed to open stream: No such file or directory File /var/local/html/dadesobertes/profiles/dkan/modules/dkan/dkan_migrate_base/dkan_migrate_base.migrate.inc, line 223, in /var/local/html/dadesobertes/profiles/dkan/modules/contrib/migrate/includes/base.inc:707
`
... etc.


My PHP version is 7.0.15

**Comment by oriole9g** [comment]
I have tested the UI install in a local environment with XAMP and PHP 5.6 and I get the same error during the install:

Migration failed with source plugin exception: file_get_contents(profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_default_content/data/group_show?id=61803702-1d76-4aac-92a1-7a4de4cd26eb.json): failed to open stream: No such file or directory File C:\wamp64\www\dkan\profiles\dkan\modules\dkan\dkan_migrate_base\dkan_migrate_base.migrate.inc, line 223, in

**Comment by fulgor** [comment]
I have just tested UI-install on a webserver with PHP 7.0 and SQLite. Had the same Ajax-Errors and still have this on every page:

> "Notice: Undefined offset: 1 in nuboot_radix_preprocess() (line 45 of /www/htdocs/SKIP-IT/DKAN/profiles/dkan/themes/nuboot_radix/includes/panel.inc)."

Installation via Composer/Drush is no option. I try DKAN because its documentation says: 

> "One of the design goals of DKAN is to make it easy for anyone with an inexpensive hosting environment to create an open data catalog." [*]

Well, shell access usually is not part of an "inexpensive hosting environment".

[1] http://docs.getdkan.com/en/latest/introduction/dkan-ckan.html

**Comment by acouch** [comment]
Pantheon offers $25 a month hosting and takes care all of the hosting elements you might need http://getdkan.com/pantheon/

Linode offers a $10 a month DIY server https://www.linode.com/pricing. It appears that even GoDaddy (which I would never recommend) [offers a CLI](https://www.godaddy.com/help/how-to-install-drush-on-cpanel-shared-hosting-12396) for their shared hosting. 

The issue [described above](https://github.com/NuCivic/dkan/issues/1732#issuecomment-282073204) appears to fixed here: #1770 

DKAN is tested and developed on Linux environments using MySQL. You can use other environments or databases that are supported by Drupal's Database Abstraction Layer but you will likely run into some issues.

I'm installing DKAN on WAMP to confirm that #1770 has resolved the issue described above. If there are separate issues a separate ticket would be optimal for tackling them.

**Comment by dafeder** [comment]
@fulgor we're working on these errors that seem to persist on the UI installer but in my experience DKAN is almost always installed and working at the end despite errors. Have you checked this?

**Comment by dafeder** [comment]
Actually I am starting to suspect that the `Notice: Undefined offset: 1 in nuboot_radix_preprocess()` error is one we haven't seen previously, and that's getting confused with other similar errors. See #1770.

**Comment by fulgor** [comment]
@acouch and @dafeder : Thank you for your answers! 
We all know, that there is nothing like an error-free software and I am glad you are working on the UI installer. Don't get me wrong, but a functioning UI installer will boost DKAN's success. Why? Because there are thousands of municipalities in Europe who hopefully will start their own open-data sites. Most of them do **not** have IT-manpower capable of using shell | composer | drush. And **none** of the local governments of these municipalities will be willing (or even allowed) to host their sites with Pantheon or Linode on US-based servers. Moreover, with increasing installation requirements for a software people will look for alternatives. See CKAN.

Aaron said "DKAN is tested and developed on Linux environments using MySQL." That's fine with me, but `dkan-drops-7` explicitly offered SQLite-support during installation. A hint in DKAN's installation-guide would be helpful. I doubt that this `nuboot_radix_preprocess()`-error will vanish with a change to MySQL. However, I will try UI install with a fresh `dkan-drop-7` on my Linux-based webspace with PHP 7 and MySQL and will drop you a note.

**Comment by oriole9g** [comment]
@fulgor I use a Linux server, MySQL amb PHP 7.0.15 and the UI Installer fails. This is not a problem with Windows or SQLite.

**Comment by acouch** [comment]
@oriole9g Thank you for your comment. I was able to reproduce the issue and have a fix here: https://github.com/NuCivic/dkan/pull/1785/files

@fulgor Thank you for the insights about the European ecosystem. I would love to hear more about how you think we can make DKAN valuable as possible in that context.

**Comment by oriole9g** [comment]
@acouch 
1) I have tested the fix in #1785 and fixes the Call to undefined function features_get_default() error!

2) In Europe we have a large number of very small municipalities, and our legislation says that our sensible data should remain in European territory, this is the reason what we doesn't use USA hostings. IMHO a simple and ready to use solution, maybe an Open Data solution with a SAAS service like Wordpress.com or Drupal Gardens with European hosting option could be a good oportunity for DKAN in this scenario.

**Comment by oriole9g** [comment]
@acouch There is a second bug that only affects the full made version project: dkan-drops-7

You have missed to push the default data json files in dkan_default_content/data. You can see all data json files un dkan repository: 
https://github.com/NuCivic/dkan/tree/7.x-1.x/modules/dkan/dkan_fixtures/modules/dkan_default_content/data

But all these json files are missing in dkan-drops-7:
https://github.com/NuCivic/dkan-drops-7/tree/master/profiles/dkan/modules/dkan/dkan_fixtures

**Comment by oriole9g** [comment]
There is a second "problem" with the dkan-drops-7 project, and I think that this can be the cause for some reporting install errors.

If you clone the full project using GIT in Windows some json files cannot be cloned and some of them are missing. 

This is a Windows/GIT problem, maybe a 255 chars path limit? 

You can see here the problem:
> $ git clone https://github.com/NuCivic/dkan-drops-7.git
Cloning into 'dkan-drops-7'...
remote: Counting objects: 321595, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 321595 (delta 6), reused 4 (delta 4), pack-reused 321585
Receiving objects: 100% (321595/321595), 144.66 MiB | 572.00 KiB/s, done.
Resolving deltas: 100% (216357/216357), done.
Checking connectivity... done.
'rror: Invalid path 'profiles/Icon
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/data_dashboard_show?id=59c96dfb-d64e-4025-b766-d9f1c7faaa47.jso
'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/data_dashboard_show?id=65ac2924-92c8-4915-b228-c7975ccb61b0.jso
'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/data_dashboard_show?id=e3fa4177-f077-46d7-8f38-5df574492d70.jso
'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/dkan_data_story_show?id=2a8542e4-84d7-4355-a8e6-f731c0eec486.js
n'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/dkan_data_story_show?id=71e0e549-4214-4297-8354-373b54468f57.js
n'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/dkan_data_story_show?id=9063c1af-460d-4755-acfc-b683953506f7.js
n'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/dkan_data_story_show?id=e27d899b-6d72-49c9-8807-b49424c4cf70.js
n'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/group_show?id=26dc023a-a216-4989-98b9-81f92d176dbd.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/group_show?id=55261028-f4b2-4402-9a30-640781ad1b59.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/group_show?id=61803702-1d76-4aac-92a1-7a4de4cd26eb.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/package_show?id=afghanistan-election-districts.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/package_show?id=crime-data-ten-most-populous-cities-us.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/package_show?id=florida-bike-lanes.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/package_show?id=gold-prices-london-1950-2008-monthly.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/package_show?id=london-deprivation-index.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/package_show?id=state-workforce-generation-2011-2015.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/package_show?id=us-national-foreclosure-statistics-january-2012
json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/package_show?id=us-tobacco-usage-statistics.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/package_show?id=varicella-chickenpox-incidence-and-mortality-an
-after-vaccine.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/package_show?id=wisconsin-polling-places.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/page_show?id=7d514bd1-fa83-4d23-bd18-6f2c9fab811b.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/page_show?id=f2e6698b-4406-47ca-9cf4-af8016ffa411.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/resource_show?id=02708727-2f2b-4567-a53f-c669c4e3b267.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/resource_show?id=0536307c-ca88-4190-a6d2-473ad08a6188.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/resource_show?id=0da191d6-4eb6-4ebe-914f-27a392087d67.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/resource_show?id=209e9f48-7c20-4654-8ba4-bd4415ee80de.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/resource_show?id=339a5d0c-ecc9-4492-8de6-30f17e91bf47.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/resource_show?id=37971f0c-a5e8-4c0c-9dbc-d6fe5fb54607.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/resource_show?id=44d9ed6f-31bc-499c-bb6c-1659f960b69d.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/resource_show?id=49daa44a-efa6-4145-92a9-baedc7202e1f.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/resource_show?id=4d6d64b8-5c1d-49b6-a222-652fd4a7cb35.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/resource_show?id=5e23aa2c-c639-49eb-b3e9-652ee22c76cb.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/resource_show?id=80d51987-acc7-42aa-a51b-9a4737c09efa.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/resource_show?id=8d533036-8f67-4c86-a3b0-bcc1c7ef6f14.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/resource_show?id=960687d8-582c-4f29-b1e4-113781e58e3b.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/resource_show?id=ae1af387-c709-4e7a-b450-c6a4e44381fb.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/resource_show?id=ca6ad242-2516-4fb0-b104-4692567f7e03.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/resource_show?id=ceb00c8e-a6d4-4dde-b8d8-43a7d714a0ff.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/resource_show?id=d59d8dfc-6015-420a-80a2-87dfdfdaf542.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/resource_show?id=e0e42cb1-e515-431f-b762-86ac46909784.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/visualization_entity_show?id=07c04d46-f787-42ae-a5f0-b563490564
e.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/visualization_entity_show?id=0a001693-167a-468f-9dcb-0aa19f98f0
7.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/visualization_entity_show?id=0d9ad70b-160e-43e4-9349-c5a8700374
b.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/visualization_entity_show?id=264f8466-acd7-47c4-876e-19f0916123
6.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/visualization_entity_show?id=29ae0e05-bb4a-4f64-8fd3-bd108a8b9c
3.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/visualization_entity_show?id=32ce3d59-5af7-4273-82ba-af4775112f
f.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/visualization_entity_show?id=334a0233-962a-4c4e-8494-cfd2799805
0.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/visualization_entity_show?id=4d7bcc14-49fc-4a4b-a01b-f74b798e6d
d.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/visualization_entity_show?id=61c94ff5-93f6-46d2-a3ec-4241012370
8.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/visualization_entity_show?id=699b8c02-ec2f-4db6-8f68-b246c34b02
c.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/visualization_entity_show?id=83df5468-ecaf-49cc-9417-c12a07531e
6.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/visualization_entity_show?id=878cbd16-586f-4057-bf87-aa81734215
8.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/visualization_entity_show?id=98970a10-64f9-4854-8fcd-1a590dea80
3.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/visualization_entity_show?id=b50c8126-8ad7-4c55-bcc4-ff1ffe801c
4.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/visualization_entity_show?id=d43ca5a9-6deb-4d00-85a3-2959603e68
3.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/visualization_entity_show?id=ebfb692a-f2f2-45f8-8b70-102e906511
5.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/visualization_entity_show?id=fe5f39cd-2d35-4eef-bad0-64c2033ead
1.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/visualization_entity_show?id=ffb38259-2841-48c0-82f4-bd20242b06
d.json'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_migrate_base/modules/dkan_
igrate_base_example/data/package_show?id=afghanistan-election-districts-test'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_migrate_base/modules/dkan_
igrate_base_example/data/package_show?id=gold-prices-london-1950-2008-monthly-t
st'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_migrate_base/modules/dkan_
igrate_base_example/data/package_show?id=us-national-foreclosure-statistics-jan
ary-2012-test'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_migrate_base/modules/dkan_
igrate_base_example/data/package_show?id=wisconsin-polling-places-test'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_migrate_base/modules/dkan_
igrate_base_example/data/resource_show?id=06f553fe-e063-44ea-afac-be0de6a9e0ca'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_migrate_base/modules/dkan_
igrate_base_example/data/resource_show?id=5df6eb37-fa44-4d29-bd67-8158aa57547e'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_migrate_base/modules/dkan_
igrate_base_example/data/resource_show?id=5fea3bdb-3138-4867-a7e8-fa1bcc182a7f'
error: Invalid path 'profiles/dkan/modules/dkan/dkan_migrate_base/modules/dkan_
igrate_base_example/data/resource_show?id=b9b0d609-b332-476b-8884-94fbc56f689a'
Checking out files: 100% (10329/10329), done.

If someone have this problems can use the download buttom from github, and get de ziped project.

**Comment by dafeder** [comment]
Huh, thanks for figuring that out @oriole9g!

**Comment by fulgor** [comment]
Ok, I just tried UI-install with a really fresh dkan-drop-7 on my Linux-based webspace with PHP 7 and this time also with MySQL. 

It was not possible to push this file to the server:
`/profiles/dkan/test/bin/behat`

During installation I've got this status message (skiped repetitions):
```
* A new user role of administrator has been added. Its permissions will be automatically managed by the Admin role module.
* The administrator role has been reset for all permissions.
* Honeypot installed successfully. Please configure Honeypot to protect your forms from spam bots.
* To use menu blocks, find the "Add menu block" link on the administer blocks page.
* You have just enabled the DKAN Topics module. Most likely you are starting with an empty Topics vocabulary. To load sample topics, enable the additional DKAN Default Topics module. Click here to manage the Topics vocabulary yourself.'
```
Then, I've got the usual Ajax-error and following the link to the error-page got a white box:
```
    Processed 3 (3 created, 0 updated, 0 failed, 0 ignored) in 0.2 sec (754/min) - done with 'dkan_default_content_groups'
    Processed 18 (18 created, 0 updated, 0 failed, 0 ignored) in 0.6 sec (1803/min) - done with 'dkan_default_content_resources'
    Processed 10 (10 created, 0 updated, 0 failed, 0 ignored) in 1.8 sec (326/min) - done with 'dkan_default_content_datasets'
    Processed 18 (18 created, 0 updated, 0 failed, 0 ignored) in 0.3 sec (3433/min) - done with 'dkan_default_content_visualization_entities'
    Processed 4 (4 created, 0 updated, 0 failed, 0 ignored) in 0.2 sec (1207/min) - done with 'dkan_default_content_data_stories'
    Processed 3 (3 created, 0 updated, 0 failed, 0 ignored) in 0.1 sec (1637/min) - done with 'dkan_default_content_data_dashboards'
    Processed 2 (2 created, 0 updated, 0 failed, 0 ignored) in 0.3 sec (375/min) - done with 'dkan_default_content_pages'
```
Followed by a green status message:
```
    The default content was imported.
    The administrator role has been reset for all permissions.
    The administrator role has been reset for all permissions.
```
Followed by this error message:
```
    Notice: Undefined index: dkan in dkan_sitewide_update_status_alter() (line 201 of /www/htdocs/[SKIP-IT]/DKAN-2/profiles/dkan/modules/dkan/dkan_sitewide/dkan_sitewide.module).
    Notice: Undefined index: existing_major in dkan_sitewide_update_status_alter() (line 216 of /www/htdocs/[SKIP-IT]/DKAN-2/profiles/dkan/modules/dkan/dkan_sitewide/dkan_sitewide.module).
    Notice: Undefined index: existing_major in dkan_sitewide_update_status_alter() (line 216 of /www/htdocs/[SKIP-IT]/DKAN-2/profiles/dkan/modules/dkan/dkan_sitewide/dkan_sitewide.module).
    Notice: Undefined index: existing_version in dkan_sitewide_update_status_alter() (line 241 of /www/htdocs/[SKIP-IT]/DKAN-2/profiles/dkan/modules/dkan/dkan_sitewide/dkan_sitewide.module).
```
## However, DKAN is up and running!
Well, on the "Home"-page the "animated gif" and all topic-icons are missing. But the rest seems to be fine.
Now I will dive into DKAN  ;-)

@acouch and @dafeder : Kudos!

**Comment by dafeder** [comment]
@oriole9g @deirdrehall the GUI install issue should be completely fixed now, let me know if you have more problems

**Comment by deirdrehall** [comment]
I pulled a fresh zip file from: https://github.com/NuCivic/dkan-drops-7 (this is the correct site, yes?) this morning and tried both a GUI install under xampp and a drush install. Neither succeeded. 

The GUI install failed with the same error as in the initial post, followed by a screen with:
Migration failed with source plugin exception: file_get_contents(profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_default_content/data/group_show?id=61803702-1d76-4aac-92a1-7a4de4cd26eb.json): failed to open stream: No such file or directory File D:\xampp\htdocs\dkan\profiles\dkan\modules\dkan\dkan_migrate_base\dkan_migrate_base.migrate.inc, line 223, in D:\xampp\htdocs\dkan\profiles\dkan\modules\contrib\migrate\includes\base.inc:707

(and etc, multiple failures similar to above).

The drush install failed with the same errors as the second above.

**Comment by dafeder** [comment]
@deirdrehall we fixed this in DKAN, but the changes won't be visible in DKAN-DROPS-7 until the next release of DKAN, which should happen in the next several days.

**Comment by deirdrehall** [comment]
Ah, thank you. Thank you. I wanted to install this locally to test out the newer version because we have another installation under Ubuntu which is having other problems, and I wanted to see if they still existed in the newest version before reporting. I will install once the new release is available.

**Comment by mohnjatthews** [comment]
@oriole9g One of the issues with Windows is that it can't deal with file names that contain question marks `?` We've been getting the same errors too, and unfortunately I can't think of a work around at the moment other than changing all the file names manually. Saying that, I imagine changing file names will have a knock-on effect.

**Comment by dafeder** [comment]
@mohnjatthews not sure which files you're referring to but we've renamed all the files in our codebase that seemed to be causing problems on Windows, that will be reflected in our next release. See #1792

**Comment by mohnjatthews** [comment]
@dafeder I was refering to the files mentioned in @oriole9g's error message: `error: Invalid path 'profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_defa
lt_content/data/group_show?id=26dc023a-a216-4989-98b9-81f92d176dbd.json'`

But since the issue's been fixed then it's all good! :+1:

**Comment by oriole9g** [comment]
Yes, I can confirm that all filenames are fine in Windows now. The next release will be Windows friendly :p

**Comment by ryanvco34** [comment]
Im using AWS Elastic Beanstalk to deploy the application, the install goes as expected. The home page returns this: 

Notice: Undefined offset: 1 in nuboot_radix_preprocess() (line 45 of /var/app/current/profiles/dkan/themes/nuboot_radix/includes/panel.inc).
Notice: Undefined offset: 1 in nuboot_radix_preprocess() (line 45 of /var/app/current/profiles/dkan/themes/nuboot_radix/includes/panel.inc).
Notice: Undefined offset: 1 in nuboot_radix_preprocess() (line 45 of /var/app/current/profiles/dkan/themes/nuboot_radix/includes/panel.inc).
Notice: Undefined offset: 1 in nuboot_radix_preprocess() (line 45 of /var/app/current/profiles/dkan/themes/nuboot_radix/includes/panel.inc).
Notice: Undefined offset: 1 in nuboot_radix_preprocess() (line 45 of /var/app/current/profiles/dkan/themes/nuboot_radix/includes/panel.inc).
Notice: Undefined offset: 1 in nuboot_radix_preprocess() (line 45 of /var/app/current/profiles/dkan/themes/nuboot_radix/includes/panel.inc).
Notice: Undefined offset: 1 in nuboot_radix_preprocess() (line 45 of /var/app/current/profiles/dkan/themes/nuboot_radix/includes/panel.inc).
